
server:
  port: 6061
  tomcat:
    max-connections: 2000 # Maximum connections
    accept-count: 200     # Maximum waiting number
  servlet:
    context-path: /
  error:
    include-stacktrace: never
    include-message: always
    include-exception: true
    include-binding-errors: always

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: users-srv
  cache:
    type: redis
    redis:
      cache-null-values: true
      use-key-prefix: true
      key-prefix: ECOMM-USER-MS
      time-to-live: 5000
  data:
    redis:
      host: localhost
      port: 6379
      ssl: 
        enabled: false
      timeout: 1000
  datasource:
    host: localhost
    port: 5432
    schemaName: ecomm_users
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.schemaName}?serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: users_service
    password: 1234
  jpa:
    open-in-view: true
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          factory_class: org.redisson.hibernate.RedissonRegionFactory
          redisson:
            fallback: true
            config: redisson-dev.yaml
        search:
          schema_management:
            strategy: create-or-validate
          automatic_indexing:
            enable_dirty_check: true
          indexing:
            listeners:
              enabled: true
            plan:
              synchronization:
                strategy: write-sync
          query:
            loading:
              fetch_size: 30
              cache_lookup:
                strategy: persistence-context-then-second-level-cache
          mapping:
            process_annotations: false
            configurer: bean:searchMappingConfigurer
          backend:
            type: elasticsearch
            hosts: localhost:9200
            protocol: http
#          backend:  # uncomment this to connect to AWS OpenSearch from local
#            type: elasticsearch
#            hosts: <opensearch endpoint>:443
#            protocol: https
#            aws:
#              signing:
#                enabled: true
#              region: us-east-1
#              credentials:
#                type: static
#                access_key_id: <value>
#                secret_access_key: <value>
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      observation-enabled: true
    template:
      observation-enabled: true

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: info, health, httptrace, loggers, metrics, threaddump
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  info:
    git:
      mode: full
  health:
    elasticsearch:
      enabled: false # if we need health check, we need to create a health indicator which will use the connection from hibernate search
    ratelimiters:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

springdoc:
  show-actuator: false
  show-login-endpoint: false
  api-docs:
    path: /api
  swagger-ui:
    path: /
    operationsSorter: method
    disable-swagger-default-url: true

resilience4j:
  ratelimiter:
    instances:
      get-all-users-endpoint: # 200 requests per minute
        limit-for-period: 200
        limit-refresh-period: 60s
        timeout-duration: 2s # blocks by 2 seconds the request which exceeded the limit
        register-health-indicator: true
      create-new-admin-user-endpoint: # 5 requests per 15 seconds
        limit-for-period: 5
        limit-refresh-period: 15s
        timeout-duration: 5s # blocks by 5 seconds the request which exceeded the limit
        register-health-indicator: true

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5p) [${spring.application.name}] [%clr(%15.15t){faint}] [%clr(%32X{traceId}-%16X{spanId}){blue}] %clr(%40.40logger{5.10}:%-4L){cyan} : %m %n'
  level:
    io.oigres.ecomm.service.users: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.internal: TRACE
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: TRACE
#    org.springframework.transaction.interceptor: TRACE
#    org.springframework.jdbc: DEBUG

ecomm:
  termsOfService: https://ecomm.oigres.io/terms/
  license: https://ecomm.oigres.io/license/
  service:
    users:
      name: EComm
      version: ${project.version}
      assets:
        bucket:
          name: ecomm-assets-dev
          rootFolder: users
          signatureDuration: 10m
        cleanup:
          cards:
            imagesTimeAfterOffset: 24h
      topics:
        entities-update: users-entities-update-topic
    tracing:
      url: http://localhost:4318/v1/traces

