name: CI
on:
  push:
    branches:
    - '**'
    
jobs:

  build-lib:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - run: mvn --batch-mode --update-snapshots install
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

# mvn jacoco:prepare-agent jacoco:report surefire:test