name: CI
on:
  push:
    branches:
    - '**'
    
jobs:

  build-app:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - run: mvn --batch-mode --update-snapshots install
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload artifacts
        id: upload-compiled-sources
        uses: actions/upload-artifact@v4.3.3
        with:
          name: compiled-sources
          path: ./
      - name: Publish users-service-api
        uses: actions/upload-artifact@v4.3.3
        with:
          name: users-service-api
          path: ./api/target/users-service-api-0.1.0-SNAPSHOT.jar
      - name: Publish users-service-sdk
        uses: actions/upload-artifact@v4.3.3
        with:
          name: users-service-sdk
          path: ./sdk/target/users-service-sdk-0.1.0-SNAPSHOT.jar
    outputs:
      compiled-sources-artifact-id: ${{ steps.upload-compiled-sources.outputs.artifact-id }}

  build-docker-image:
    name: Create docker image
    needs: [build-app]
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled sources
        uses: actions/download-artifact@v4.1.7
        with:
          name: compiled-sources
          path: ./
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: sjexposecomm/users-service:latest

  delete-unused-artifact:
    name: Delete unused artifact
    needs: [build-app, build-docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: Delete Artifact
        uses: actions/github-script@v7
        with:
          script: |
              github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: ${{ needs.build-app.outputs.compiled-sources-artifact-id }}
              });

# mvn jacoco:prepare-agent jacoco:report surefire:test
